// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.26.1
// source: gmessage.proto

package graphsync_message_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// the actual data included in this message
	CompleteRequestList bool                `protobuf:"varint,1,opt,name=completeRequestList,proto3" json:"completeRequestList,omitempty"` // This request list includes *all* requests, replacing outstanding requests.
	Requests            []*Message_Request  `protobuf:"bytes,2,rep,name=requests,proto3" json:"requests,omitempty"`                        // The list of requests.
	Responses           []*Message_Response `protobuf:"bytes,3,rep,name=responses,proto3" json:"responses,omitempty"`                      // The list of responses.
	Data                []*Message_Block    `protobuf:"bytes,4,rep,name=data,proto3" json:"data,omitempty"`                                // Blocks related to the responses
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_gmessage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_gmessage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_gmessage_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetCompleteRequestList() bool {
	if x != nil {
		return x.CompleteRequestList
	}
	return false
}

func (x *Message) GetRequests() []*Message_Request {
	if x != nil {
		return x.Requests
	}
	return nil
}

func (x *Message) GetResponses() []*Message_Response {
	if x != nil {
		return x.Responses
	}
	return nil
}

func (x *Message) GetData() []*Message_Block {
	if x != nil {
		return x.Data
	}
	return nil
}

type Message_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                                                                          // unique id set on the requester side
	Root          []byte                 `protobuf:"bytes,2,opt,name=root,proto3" json:"root,omitempty"`                                                                                       // a CID for the root node in the query
	Selector      []byte                 `protobuf:"bytes,3,opt,name=selector,proto3" json:"selector,omitempty"`                                                                               // ipld selector to retrieve
	Extensions    map[string][]byte      `protobuf:"bytes,4,rep,name=extensions,proto3" json:"extensions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // aux information. useful for other protocols
	Priority      int32                  `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`                                                                              // the priority (normalized). default to 1
	Cancel        bool                   `protobuf:"varint,6,opt,name=cancel,proto3" json:"cancel,omitempty"`                                                                                  // whether this cancels a request
	Update        bool                   `protobuf:"varint,7,opt,name=update,proto3" json:"update,omitempty"`                                                                                  // whether this requests resumes a previous request
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message_Request) Reset() {
	*x = Message_Request{}
	mi := &file_gmessage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_Request) ProtoMessage() {}

func (x *Message_Request) ProtoReflect() protoreflect.Message {
	mi := &file_gmessage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_Request.ProtoReflect.Descriptor instead.
func (*Message_Request) Descriptor() ([]byte, []int) {
	return file_gmessage_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Message_Request) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Message_Request) GetRoot() []byte {
	if x != nil {
		return x.Root
	}
	return nil
}

func (x *Message_Request) GetSelector() []byte {
	if x != nil {
		return x.Selector
	}
	return nil
}

func (x *Message_Request) GetExtensions() map[string][]byte {
	if x != nil {
		return x.Extensions
	}
	return nil
}

func (x *Message_Request) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Message_Request) GetCancel() bool {
	if x != nil {
		return x.Cancel
	}
	return false
}

func (x *Message_Request) GetUpdate() bool {
	if x != nil {
		return x.Update
	}
	return false
}

type Message_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                                                                          // the request id
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`                                                                                  // a status code.
	Extensions    map[string][]byte      `protobuf:"bytes,3,rep,name=extensions,proto3" json:"extensions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // additional data
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message_Response) Reset() {
	*x = Message_Response{}
	mi := &file_gmessage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_Response) ProtoMessage() {}

func (x *Message_Response) ProtoReflect() protoreflect.Message {
	mi := &file_gmessage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_Response.ProtoReflect.Descriptor instead.
func (*Message_Response) Descriptor() ([]byte, []int) {
	return file_gmessage_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Message_Response) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Message_Response) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Message_Response) GetExtensions() map[string][]byte {
	if x != nil {
		return x.Extensions
	}
	return nil
}

type Message_Block struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        []byte                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"` // CID prefix (cid version, multicodec and multihash prefix (type + length)
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message_Block) Reset() {
	*x = Message_Block{}
	mi := &file_gmessage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message_Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_Block) ProtoMessage() {}

func (x *Message_Block) ProtoReflect() protoreflect.Message {
	mi := &file_gmessage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_Block.ProtoReflect.Descriptor instead.
func (*Message_Block) Descriptor() ([]byte, []int) {
	return file_gmessage_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Message_Block) GetPrefix() []byte {
	if x != nil {
		return x.Prefix
	}
	return nil
}

func (x *Message_Block) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_gmessage_proto protoreflect.FileDescriptor

const file_gmessage_proto_rawDesc = "" +
	"\n" +
	"\x0egmessage.proto\x12\x14graphsync.message.pb\"\xac\x06\n" +
	"\aMessage\x120\n" +
	"\x13completeRequestList\x18\x01 \x01(\bR\x13completeRequestList\x12A\n" +
	"\brequests\x18\x02 \x03(\v2%.graphsync.message.pb.Message.RequestR\brequests\x12D\n" +
	"\tresponses\x18\x03 \x03(\v2&.graphsync.message.pb.Message.ResponseR\tresponses\x127\n" +
	"\x04data\x18\x04 \x03(\v2#.graphsync.message.pb.Message.BlockR\x04data\x1a\xab\x02\n" +
	"\aRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04root\x18\x02 \x01(\fR\x04root\x12\x1a\n" +
	"\bselector\x18\x03 \x01(\fR\bselector\x12U\n" +
	"\n" +
	"extensions\x18\x04 \x03(\v25.graphsync.message.pb.Message.Request.ExtensionsEntryR\n" +
	"extensions\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\x05R\bpriority\x12\x16\n" +
	"\x06cancel\x18\x06 \x01(\bR\x06cancel\x12\x16\n" +
	"\x06update\x18\a \x01(\bR\x06update\x1a=\n" +
	"\x0fExtensionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\x1a\xc9\x01\n" +
	"\bResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12V\n" +
	"\n" +
	"extensions\x18\x03 \x03(\v26.graphsync.message.pb.Message.Response.ExtensionsEntryR\n" +
	"extensions\x1a=\n" +
	"\x0fExtensionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\x1a3\n" +
	"\x05Block\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\fR\x06prefix\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04dataB\x18Z\x16.;graphsync_message_pbb\x06proto3"

var (
	file_gmessage_proto_rawDescOnce sync.Once
	file_gmessage_proto_rawDescData []byte
)

func file_gmessage_proto_rawDescGZIP() []byte {
	file_gmessage_proto_rawDescOnce.Do(func() {
		file_gmessage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gmessage_proto_rawDesc), len(file_gmessage_proto_rawDesc)))
	})
	return file_gmessage_proto_rawDescData
}

var file_gmessage_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_gmessage_proto_goTypes = []any{
	(*Message)(nil),          // 0: graphsync.message.pb.Message
	(*Message_Request)(nil),  // 1: graphsync.message.pb.Message.Request
	(*Message_Response)(nil), // 2: graphsync.message.pb.Message.Response
	(*Message_Block)(nil),    // 3: graphsync.message.pb.Message.Block
	nil,                      // 4: graphsync.message.pb.Message.Request.ExtensionsEntry
	nil,                      // 5: graphsync.message.pb.Message.Response.ExtensionsEntry
}
var file_gmessage_proto_depIdxs = []int32{
	1, // 0: graphsync.message.pb.Message.requests:type_name -> graphsync.message.pb.Message.Request
	2, // 1: graphsync.message.pb.Message.responses:type_name -> graphsync.message.pb.Message.Response
	3, // 2: graphsync.message.pb.Message.data:type_name -> graphsync.message.pb.Message.Block
	4, // 3: graphsync.message.pb.Message.Request.extensions:type_name -> graphsync.message.pb.Message.Request.ExtensionsEntry
	5, // 4: graphsync.message.pb.Message.Response.extensions:type_name -> graphsync.message.pb.Message.Response.ExtensionsEntry
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_gmessage_proto_init() }
func file_gmessage_proto_init() {
	if File_gmessage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gmessage_proto_rawDesc), len(file_gmessage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gmessage_proto_goTypes,
		DependencyIndexes: file_gmessage_proto_depIdxs,
		MessageInfos:      file_gmessage_proto_msgTypes,
	}.Build()
	File_gmessage_proto = out.File
	file_gmessage_proto_goTypes = nil
	file_gmessage_proto_depIdxs = nil
}
